version: '3.8'

services:
  mongo:
    env_file: .env
    image: mongo:latest
    # ports:
    #   - "${MONGO_PORT}:27017" # Exposed only internally in the network
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  redis:
    env_file: .env
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    env_file: .env
    build: ../backend
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_URL=${REDIS_URL}
      - CSV_IMPORT_URL=${CSV_IMPORT_URL}
    depends_on:
      - mongo
      - redis
    volumes:
      - ../backend:/app
    networks:
      - app_network

  celery-worker:
    env_file: .env
    build: ../backend
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_URL=${REDIS_URL}
      - CSV_IMPORT_URL=${CSV_IMPORT_URL}
    depends_on:
      - mongo
      - redis
      - backend
    volumes:
      - ../backend:/app
    networks:
      - app_network

  celery-beat:
    env_file: .env
    build: ../backend
    command: celery -A app.celery_app beat --loglevel=info
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_URL=${REDIS_URL}
      - CSV_IMPORT_URL=${CSV_IMPORT_URL}
    depends_on:
      - mongo
      - redis
      - backend
    volumes:
      - ../backend:/app
    networks:
      - app_network

  frontend:
    env_file: .env
    build: ../frontend
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge

